export const refs = {
  deliveryForm: document.querySelector('.deliveries-form-js'),
  deliveryNumber: document.querySelector('.delivery-no-number'),
  deliveryNumberYear: document.querySelector('.delivery-no-year'),
  deliveriesDate: document.querySelector('.deliveries-form-date-js'),
  fullDeliveryNo: document.querySelector('.full-delivery-no-js'),
  recipientName: document.querySelector('.recipient-name-user-login'),
  userDeliveryDescr: document.querySelector('.delivery-descr-js'),
  deleteDeliveryForm: document.querySelector('.delete-delivery-form-js'),
  tableBody: document.querySelector('.deliveries-table-body'),
  incShipID: document.querySelector('.inc-ship-id'),
  updateDeliveryBtn: document.querySelector('.update-delivery-btn'),
  updateDeliveryOverlay: document.querySelector('.update-delivery-overlay'),
  modalWindowCloseBtn: document.querySelector('.modal-window-close-btn'),
  tableBody: document.querySelector('.deliveries-table-body'),
  deliveriesTime: document.querySelector('.deliveries-form-time-js'),
  updateDeliverySelect: document.querySelector('.update-delivery-select-js'),
  inputContainer: document.querySelector('.input-container'),
  updateDeliveryForm: document.querySelector('.modal-update-delivery-form-js'),
};
